config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  devise_for :users, :skip => :registrations

  mount RailsAdmin::Engine => '/mabika', as: 'rails_admin'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/makoumbou'
  end

  root 'home#index'

  get '/contact', to: 'home#contact', as: :contact

  get '/videos', to: 'videos#index', as: :videos_index
  get '/songs', to: 'songs#index', as: :songs_index
  get '/albums', to: 'albums#index', as: :albums_index

  get '/artists', to: 'artists#index', as: :artists_index
  get '/artists/:id', to: 'artists#show', as: :artists_root

end

app/views/lol/newsessions.html.erb
<div class="sixteen wide mobile eight wide tablet eight wide computer centered column">
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="ui inverted form">
      <h4 class="ui header">Log In</h4>
      <div class="ui divider"></div>
      <div class="field">
        <%= f.label :email %>
        <div class="ui icon input">
          <%= f.email_field :email, autofocus: true %>
          <i class="user icon"></i>
        </div>
      </div>
      <div class="field">
        <%= f.label :password %>
        <div class="ui icon input">
          <%= f.password_field :password, autocomplete: "off" %>
          <i class="lock icon"></i>
        </div>
      </div>
      <% if devise_mapping.rememberable? -%>
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      <% end -%>
      <%= f.submit "Log in", class: "ui button" %>
    </div>
  <% end %>
  <%= render "devise/shared/links" %>
</div>

app/views/lol/passowrdedit.html.erb
<div class="sixteen wide mobile eight wide tablet eight wide computer centered column">
  <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do |f| %>
    <div class="ui inverted form">
      <%= devise_error_messages! %>
      <%= f.hidden_field :reset_password_token %>
      <h4 class="ui header">Change your password</h4>
      <div class="ui divider"></div>
      <div class="field">
        <%= f.label :password, "New password" %>
        <div class="ui icon input">
          <%= f.password_field :password, autofocus: true, autocomplete: "off" %>
          <i class="lock icon"></i>
        </div>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, "Confirm new password" %>
        <div class="ui icon input">
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
          <i class="lock icon"></i>
        </div>
      </div>
      <%= f.submit "Change my password", class: "ui button" %>
    </div>
  <% end %>
  <%= render "devise/shared/links" %>
</div>

app/views/lol/passwordnew.html.erb
<div class="sixteen wide mobile eight wide tablet eight wide computer centered column">
	<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
	  <div class="ui inverted form">
	  	<%= devise_error_messages! %>
	    <h4 class="ui header">Forgot your password?</h4>
	    <div class="ui divider"></div>
		  <div class="field">
			  <%= f.label :email %>
			  <div class="ui icon input">
			    <%= f.email_field :email, autofocus: true %>
			    <i class="user icon"></i>
			  </div>
	    </div>
	  	<%= f.submit "Send me reset password instructions", class: "ui button" %>
	  </div>
	<% end %>
	<%= render "devise/shared/links" %>
</div>