config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  devise_for :users, :skip => :registrations

  mount RailsAdmin::Engine => '/mabika', as: 'rails_admin'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/makoumbou'
  end

  root 'home#index'

  get '/contact', to: 'home#contact', as: :contact

  get '/videos', to: 'videos#index', as: :videos_index
  get '/songs', to: 'songs#index', as: :songs_index
  get '/albums', to: 'albums#index', as: :albums_index

  get '/artists', to: 'artists#index', as: :artists_index
  get '/artists/:id', to: 'artists#show', as: :artists_root

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id           :integer          not null, primary key
#  name         :string
#  key          :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  channel_id   :integer
#  published_at :datetime
#  artist_id    :integer
#

class Video < ActiveRecord::Base
	belongs_to :channel
	belongs_to :artist

	def artist_name
		artist.name
	end

	validates :name, presence: true
	validates :key, presence: true
	validates :published_at, presence: true
	validates :channel_id, presence: true
	validates :artist_id, presence: true

	rails_admin do
    list do
      filters [:artist]
      field :artist
      field :name
    end
    update do
      field :name
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  	@videos = Video.order(published_at: :desc, created_at: :desc).page(params[:page]).per(126)
  end
end

app/views/videos/_video.html.erb
<tr>
	<td><div class="ui large red horizontal label">Video</div></td>
	<td><h4 class="ui header"><%= video.published_at.strftime("%B %d, %Y") %></h4></td>
	<td><%= link_to video.name, "https://www.youtube.com/watch?v=#{video.key}", :target => "_blank" %></td>
	<td><%= link_to video.channel.artist.name, artists_root_path(video.channel.artist) %></td>
</tr>

app/views/videos/_videos.html.erb
<table id="videos" class="ui large table">
	<%= render @videos %>
</table>
<div class="ui hidden divider"></div>
<div id="pagination">
  <%= link_to_next_page(@videos, 'Show More', :remote => true, class: "fluid ui button more-button") %>
</div>

app/views/videos/index.html.erb
<% provide(:title, 'Videos') %>

<div class="sixteen wide column">
	<h2 class="ui center aligned header red header">Videos</h2>
	<%= render 'videos/videos' %>
</div>

app/views/videos/index.js.erb
$("<%=j render @videos %>").appendTo($("#videos"));
// Update pagination link
<% if @videos.last_page? %>
	$('#pagination').html("<h3 class='ui center aligned header'>The End</h3>");
<% else %>
  $('#pagination')
    .html("<%=j link_to_next_page(@videos, 'Show More', :remote => true, class: 'fluid ui button more-button') %>");
<% end %>