config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  devise_for :users, :skip => :registrations

  mount RailsAdmin::Engine => '/mabika', as: 'rails_admin'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/makoumbou'
  end

  root 'home#index'

  get '/contact', to: 'home#contact', as: :contact

  get '/videos', to: 'videos#index', as: :videos_index
  get '/songs', to: 'songs#index', as: :songs_index
  get '/albums', to: 'albums#index', as: :albums_index

  get '/artists', to: 'artists#index', as: :artists_index
  get '/artists/:id', to: 'artists#show', as: :artists_root

end

app/views/layouts/_footer.html.erb
<div class="ui inverted fixed bottom large three item menu">
	<%= link_to videos_index_path, class: "item" do %>
    <i class="red video play icon"></i>Videos</a>
  <% end %>
	<%= link_to songs_index_path, class: "item" do %>
    <i class="red music icon"></i>Songs</a>
  <% end %>
		<%= link_to albums_index_path, class: "item" do %>
    <i class="red sound icon"></i>Albums</a>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<div class="sixteen wide column">
	<div class="ui hidden divider"></div>
	<%- flash.each do |name, msg| -%>
	  <div class="ui red message">
	  	<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	  </div>
	<%- end -%>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui inverted fixed top large three item menu">
	<%= link_to artists_index_path, class: "item" do %>
    <i class="red users icon"></i>Artists</a>
  <% end %>
	<%= link_to root_path, class: "item" do %>
    <i class="red home icon"></i>Hiphoplog</a>
  <% end %>
  <% if user_signed_in? && current_user.admin? %>
  	<%= link_to rails_admin_path, class: "item" do %>
    	<i class="red privacy icon"></i>Admin</a>
  	<% end %>
	<% else %>
  	<%= link_to contact_path, class: "item" do %>
  		<i class="red mail icon"></i>Contact</a>
  	<% end %>
	<% end %>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--   <meta name="description" content="Hiphoplog"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div id="main" class="ui page grid">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>